import{a as E,S as b,i as n}from"./assets/vendor-BDaiwwc1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const B="47432797-7b7ae49ed8d9ca3634e43854b",P="https://pixabay.com/api/",m=async(r,e=1)=>{const a=new URLSearchParams({key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});try{return(await E.get(`${P}?${a}`)).data.hits}catch{throw new Error("Failed to fetch images")}};let h;const M=r=>r.map(e=>`
    <li class="li">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="div">
        <p class="p">Likes: ${e.likes}</p>
        <p class="p">Views: ${e.views}</p>
        <p class="p">Comments: ${e.comments}</p>
        <p class="p">Downloads: ${e.downloads}</p>
      </div>
    </li>
  `).join(""),f=(r,e,a=!1)=>{const o=M(e);a?r.insertAdjacentHTML("beforeend",o):r.innerHTML=o,h?h.refresh():h=new b(".gallery a")},p=document.getElementById("search-form"),l=document.getElementById("gallery"),g=document.getElementById("loader"),u=document.getElementById("load-more");let i="",c=1;const y=()=>g.classList.remove("hidden"),L=()=>g.classList.add("hidden"),w=()=>u.classList.remove("hidden"),v=()=>u.classList.add("hidden"),S=async r=>{if(r.preventDefault(),i=p.elements["search-input"].value.trim(),!i){n.error({title:"Error",message:"Please enter a search query!"});return}c=1,l.innerHTML="",v(),y();try{const e=await m(i,c);e.length===0?n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(f(l,e),e.length===15&&w())}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{L()}},$=async()=>{c+=1,y(),v();try{const r=await m(i,c);f(l,r,!0),r.length===15?w():n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."});const{height:e}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{L()}};p.addEventListener("submit",S);u.addEventListener("click",$);
//# sourceMappingURL=index.js.map
